### ISSUE TITLE
TypeError: e.apply is not a function

### ISSUE THREAD

**Issue by helrond** [vytenisu/use-chat-scroll#1] opened 2021-09-27 22:12 UTC
Attempting to get this hook working but am running into an error that's generic enough that I'm not sure how to address it.

```
import React, { useRef, useState } from 'react'
import {useChatScroll, useDataLoader} from 'use-chat-scroll'

const initialData = [
  {
    "title": "AS 9119 - DIOUF, JACQUES",
  },
  {
    "title": "AS 9124 - SEMOKA, JOHNSON MASHAMBA R.",
  },
  {
    "title": "AS 9125 - THAILAND DEVELOPMENT RESEARCH INSTITUTE FOUNDATION - AGRICHEMICAL USE IMPACT",
  },
  {
    "title": "AS 9126 - EDUARDO MONDLANE UNIVERSITY - STRENGTHENING TRAINING CAPACITY",
  },
  {
    "title": "AS 9129 - MUFANDAEDZA, ONEAS TICHAFA",
  }
]

const loadAdditionalData = []

const Scroll = () => {
  const [data, setData] = useState(initialData)
  const containerRef = useRef()
  const loader = useDataLoader(loadAdditionalData, data, setData)
  useChatScroll(containerRef, data, loader)

  return (
    <div ref={containerRef} style={{height: "100px", width: "100%", overflow: 'auto'}}>
      {data.map(item => (
        <p key={item.title}>{item.title}</p>
      ))}
    </div>
  )
}

export default Scroll
```
When scrolling to the top of the component, I'm getting the following error:
```
 Uncaught (in promise) TypeError: e.apply is not a function
    at Object.<anonymous> (data-loader.ts:32)
    at chat-scroll.ts:52
    at Object.next (chat-scroll.ts:52)
    at chat-scroll.ts:52
    at new Promise (<anonymous>)
    at r (chat-scroll.ts:52)
    at Object.current (data-loader.ts:31)
    at Object.<anonymous> (reverse-infinite-scroll.ts:53)
    at scroll.ts:19
    at Object.next (scroll.ts:19)
    at scroll.ts:19
    at new Promise (<anonymous>)
    at r (scroll.ts:19)
    at HTMLDivElement.M (reverse-infinite-scroll.ts:52)
```
Any idea what I'm doing wrong?

**Comment by vytenisu** [comment] 2021-09-29 11:33
Hi, I will have a look some time soon and get back to you. Thank you for reporting.

**Comment by vytenisu** [comment] 2021-09-29 11:51
loadAdditionalData is supposed to be a callback for getting additional data. For mocking purposes you would want to write it like this:

`const loadAdditionalData = () => []`

I would strongly suggest using TypeScript to avoid such issues in the future. This NPM module brings types with it and can catch such errors at build time.

**Comment by vytenisu** [comment] 2021-09-29 11:52
Closing issue since I reproduced it and found a solution. Feel free to re-open if needed.

**Closed as completed by vytenisu** 2021-09-29 11:52 UTC

**Comment by helrond** [comment] 2021-09-29 13:54
Thanks @vytenisu - that's how you had it written in the README too, so I must have just been having a stupid day.

**Comment by WhiteTurbine** [comment] 2021-09-29 20:50
@helrond , no problem :) just hope it is useful for you. I am thinking of improving the API one day also to make it simpler. But still, current version should also do the trick.
